# Generated by Django 6.0 on 2026-01-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DelayAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('delay_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delay_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('delay_reason', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('active_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('total_hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('average_efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('tasks_assigned', models.PositiveIntegerField(default=0)),
                ('hours_logged', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkillRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('total_hours_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_hours_actual', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_task_duration', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskPerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('summary_data', models.JSONField(default=dict)),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkloadDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_tasks_count', models.PositiveIntegerField(default=0)),
                ('total_estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('overdue_tasks_count', models.PositiveIntegerField(default=0)),
                ('workload_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
