# Generated by Django 6.0 on 2026-01-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayanalysis',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delay_analysis', to='tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentanalytics',
            unique_together={('department', 'date')},
        ),
    ]
