# Generated by Django 6.0 on 2026-01-10 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeproductivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivity_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeskillrating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeskillrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectanalytics',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='tasks.project'),
        ),
        migrations.AddField(
            model_name='taskperformancereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workloaddistribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='employeeproductivity',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeskillrating',
            unique_together={('user', 'skill_name', 'rated_by')},
        ),
        migrations.AlterUniqueTogether(
            name='workloaddistribution',
            unique_together={('user', 'date')},
        ),
    ]
